[Storage]Fix cdi_config_test
Fix error:
    def __init__(self, func, args, kwds):
>       self.gen = func(*args, **kwds)
E       TypeError: upload_image_to_dv() missing 1 required positional argument: 'client'

Change-Id: I288ce4f62a589d449a327d9da90fcd257260cc98