Revert "Add support for calling ansible modules from pytest"
This reverts commit 91bd0f45be82f6921cd6d4c347215f92325a49a6.

Fail to run pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --ansible-host-pattern tests/network/connectivity/linux_bridge/
  inifile: /root/cnv-tests/pytest.ini
  rootdir: /root/cnv-tests

Change-Id: Ib3121ee6ef376db70b706e797759a3555bb43bd9
Reviewed-on: https://code.engineering.redhat.com/gerrit/174010
Reviewed-by: Meni Yakove <myakove@redhat.com>
Continuous-Integration: Meni Yakove <myakove@redhat.com>
Tested-by: Meni Yakove <myakove@redhat.com>