[Storage] Fix CNV-3516
Add step for waiting the clone dv to CloneInProgress
Sometime the test failed with "AttributeError: 'NoneType' object has no attribute 'wait_for_status'"
due to the pod was not created at the moment

Change-Id: I2ef8bcaaa701d571cd170ed43d5ee472cf93c02f