Need to force drain the nodes for migration.
Been some changes around node drain.
We see the below erro without the --force option.

error: cannot delete Pods not managed by
ReplicationController, ReplicaSet, Job, DaemonSet or
StatefulSet (use --force to override):

Change-Id: I62d09c1d6c1a13e1e23ffc9d572c1d8b82e09e4a
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>