[Storage] Fix case CNV-2451 CNV-2478
Fix the error :
E       TypeError: upload_image_to_dv() missing 1 required positional argument: 'storage_class'

Update the volume_mode to Filesystem for HPP

Change-Id: I93bd4610ef3fd1ebeab2f07e18897941203b43dd